### ISSUE TITLE
Marathon is Deprecated, future plans for Puma?

### ISSUE THREAD

**Issue by Sajjon** [pumaswift/Puma#12]
Hey! I have not tried Puma yet, but I'm excited about the idea of moving from the Ruby (talking about `fastlane` ofc) domain to the Swift domain :D 

Anyway, [Marathon is **deprecated**](https://github.com/JohnSundell/Marathon), how does this affect Puma?

**Comment by onmyway133** [comment]
@Sajjon Hi, glad that you check out Puma. In my PR https://github.com/pumaswift/Puma/pull/13 I've removed the mention of Marathon as it didn't work for my colleagues. In the example, there is no a macOS project that you can try Puma out.
