### ISSUE TITLE
macOS Support

### ISSUE THREAD

**Issue by mRs-** [pumaswift/Puma#16]
Is there a plan to support macOS?

**Comment by onmyway133** [comment]
@mRs- Hi, you mean the tool itself to be supported on macOS server? Or to support macOS project? If it is about macOS project, then this is very universal as it is using xcodebuild under the hood

**Comment by mRs-** [comment]
Currently I'm using xcodebuild in a makefile to build and publish my macOS App

**Comment by onmyway133** [comment]
@mRs- ja, that's great. This tool is just a wrapper around xcodebuild, and some sugar

**Comment by mRs-** [comment]
I will try to implement my current workflow in Puma

**Comment by onmyway133** [comment]
@mRs- ja, Puma is in its very early development, if you like to collaborate I'm very happy to invite you
