### ISSUE TITLE
Slack support

### ISSUE THREAD

**Issue by skyylex** [pumaswift/Puma#37]
Hi,

I've started analyzing what is required to enable Slack support and there are quite different options, depending on whether additional dependencies are allowed or not (how many of them, etc). More concretely, I've found this awesome library SlackKit - https://github.com/pvzig/SlackKit, however it pulls quite a few dependencies like:

- Swifter
- WebSocker
- Starscream
- Vapor (Core, Crypto, HTTP)
- swift-nio (ssl, zlib)

Does it make sense to continue with SlackKit or there any guidelines / restrictions?

Thanks in advance.

**Comment by skyylex** [comment]
Just found Slack class in Core / Tasks. I think my question doesn't make sense anymore :). I've created a PR to update Roadmap in README - https://github.com/pumaswift/Puma/pull/39.

**Comment by onmyway133** [comment]
@skyylex Hi, I know SlackKit offers lots more, in this  case I just want a quick way to post something to Slack so my Slack task is just simple HTTP request. But given the Task protocol, we can extend later
